on:
  release:
    types:
      - released
jobs:
  build-sbom:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: anchore/sbom-action@v0
